[package]
name = "femto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
crossterm = "0.25.0"
log = "0.4"
simplelog = "0.12.0"
